FROM node:alpine as BUILD_IMAGEWORKDIR /appCOPY package.json yarn.lock ./# install dependencies
RUN yarn install --frozen-lockfileCOPY . .# build
RUN yarn build# remove dev dependencies
RUN npm prune --productionFROM node:alpineWORKDIR /app# copy from build image
COPY --from=BUILD_IMAGE /app/package.json ./package.json
COPY --from=BUILD_IMAGE /app/node_modules ./node_modules
COPY --from=BUILD_IMAGE /app/.next ./.next
COPY --from=BUILD_IMAGE /app/public ./publicEXPOSE 3000
CMD ["yarn", "start"]