FROM node:18-alpine as builder
# Set the working directory to /app inside the container
WORKDIR /app
# Copy app files
COPY . .
# Install dependencies (npm ci makes sure the exact versions in the lockfile gets installed)
RUN npm install 
# Build the app
RUN npm run build

# Expose port
EXPOSE 80
# Start app
CMD ["next", "dev"]