version: '3.8'
services:
  db:
    env_file: .env
    image: postgres:13-alpine
    container_name: pgstore
    hostname: pgstore
    restart: always
    environment:
      - POSTGRES_USER=${PG_STORE_USER}
      - POSTGRES_PASSWORD=${PG_STORE_PASSWORD}
      - POSTGRES_DB=${PG_STORE_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  clap:
    container_name: clap
    build:
      context: ./backend/clap
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8000:8000

volumes:
  db:
    driver: local
