version: '3.8'

services:

  db:
    image: postgres:13-alpine
    container_name: pgstore
    hostname: pgstore
    restart: always
    environment:
      - POSTGRES_USER=${PG_STORE_USER}
      - POSTGRES_PASSWORD=${PG_STORE_PASSWORD}
      - POSTGRES_DB=${PG_STORE_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  
  frontend:
    container_name: frontend
    build: ./frontend
    restart: on-failure
    ports:
      - 3000:3000
    networks:
        - full-stack-app
  
  clap:
    container_name: clap
    build: ./backend/clap/clap
    restart: on-failure
    ports:
      - 8000:8000
    networks:
      - full-stack-app

volumes:
  db:
    driver: local

networks:
  full-stack-app:
