services:
  db:
    env_file: .env
    image: postgres:13-alpine
    container_name: pgstoree
    hostname: pgstore
    restart: always
    environment:
      - POSTGRES_USER=${PG_STORE_USER}
      - POSTGRES_PASSWORD=${PG_STORE_PASSWORD}
      - POSTGRES_DB=${PG_STORE_DATABASE}
    ports:
      - '5431:5432'
    volumes:
      - db:/var/lib/postgresql/data

  # dstor:
  #   env_file: .env
  #   container_name: dstor
  #   build:
  #     context: ./backend/data-store
  #     dockerfile: Dockerfile
  #   restart: on-failure
  #   ports:
  #     - 8080:8080

  ## THIS DOES NOT WORK, TO BE FIXED:
  # frontend:
  #   container_name: frontend
  #   build: ./frontend
  #   restart: on-failure
  #   ports:
  #     - 3000:3000
  #   networks:
  #       - full-stack-app

  # THIS DOES NOT WORK, TO BE FIXED:
  clap:
    container_name: clap
    build:
      context: ./backend/clap
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8000:8000

volumes:
  db:
    driver: local
