version: '3.8'
services:
  db:
    env_file: .env
    image: postgres:13-alpine
    container_name: pgstore
    hostname: pgstore
    restart: always
    # paste here real data or set in system environment
    environment:
      - POSTGRES_USER=${PG_STORE_USER}
      - POSTGRES_PASSWORD=${PG_STORE_PASSWORD}
      - POSTGRES_DB=${PG_STORE_DATABASE}
    ports:
      - '5431:5432'
    volumes:
      - db:/var/lib/postgresql/data

  dstor:
    env_file: .env
    container_name: dstor
    build:
      context: ./backend/data-store
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
    ports:
      - '8080:8080'

  clap:
    container_name: clap
    env_file: .env
    build:
      context: ./backend/clap
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - dstor
    ports:
      - '8000:8000'
    environment:
      FRONTEND.ADDRESS: http://frontend:3000
      GRPC.CLIENT.DATASTORE.ADDRESS: static://dstor:8080

  # Correct if you need
  frontend:
    container_name: frontend
    depends_on:
      - clap
    build: ./frontend
    restart: on-failure
    ports:
      - '3000:3000'

volumes:
  db:
    driver: local
