grpc:
  client:
    myService:
      address: static://localhost:6565
      negotiationType: plaintext
server:
  port: 8000

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://zpi-ist-fcbee.firebaseapp.com
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
