grpc:
  client:
    dataStore:
      address: static://localhost:8080
      negotiationType: plaintext
server:
  port: 8000

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com

frontend:
  address: http://frontend:3000

firebase:
  issuer: https://securetoken.google.com/zpi-ist-fcbee
  audience: zpi-ist-fcbee
