version: '3.8'
services:
  db:
    image: postgres:13-alpine
    container_name: pgstore
    hostname: pgstore
    restart: always
    environment:
      - POSTGRES_USER=${PG_STORE_USER}
      - POSTGRES_PASSWORD=${PG_STORE_PASSWORD}
      - POSTGRES_DB=${PG_STORE_DATABASE}
    ports:
      - '5431:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
