name: build-docker-compose
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Copy .env.template to .env
        run: |
          cp .env.template .env
      - name: Set Postgres env variables 
        run: |
          sed -i 's/POSTGRES_USER=postgres/POSTGRES_USER=postgres/g' .env
          sed -i 's/POSTGRES_PASSWORD=postgres/POSTGRES_PASSWORD=postgres/g' .env
          sed -i 's/POSTGRES_DB=postgres/POSTGRES_DB=postgres/g' .env

      - name: Build Docker Compose images
        run: |
          docker-compose build
